# Generated by Django 4.1.3 on 2022-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_file_tb_size_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_tb',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
