# Generated by Django 4.1.3 on 2023-02-11 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_file_tb_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_tb',
            name='id_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
